= Contributing
Gopal S Akshintala <gopalakshintala@gmail.com>
:Revision: 1.0
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:hide-uri-scheme:
:imagesdir: images
:toc:

[#_versioning_strategy]
== Versioning Strategy

====
<A>.<B>.<C>
====

* A = We broke something on purpose (Breaking API change)
* B = Profit (Feature / Improvement)
* C = We broke something by accident (Bug)

== Source-code Setup

=== Install Java 25

Vador requires JDK 25. The repository's `.sdkmanrc` pins the development runtime.
After installing https://sdkman.io/install[SDKMAN], run:

[source,bash]
----
sdk env install
----

=== Build with Gradle

* This is a simple Gradle project and has its own Gradle wrapper. So nothing to install. Just run this command

Gradle uses the standard `src/main/kotlin` production source layout and automatically generates the public Java API.

[source,bash]
----
./gradlew clean build
----

TIP: You *don't* need a local Gradle installation as the `gradlew` (Gradle wrapper) takes care of everything. But if you wish to install gradle locally, the recommendation is to  do it via https://sdkman.io/install[SDKMAN]. After you install SDKMAN, run `sdk install gradle` to install Gradle

* You can run/debug the existing unit tests or write your own to play with Vador.

=== Kotlin

* Handwritten production source is Kotlin, while Java consumers remain supported.
If you're a Java developer and new to Kotlin, don't worry, Kotlin is a JVM language and can be used anywhere Java is used.
In fact, it has got the reputation of *"Better Java!"*.
* A typical Java developer can ramp up on Kotlin in less than a week. These resources can help catalyze your ramp-up:
** https://play.kotlinlang.org/byExample/overview[Learn Kotlin by Example]
** https://www.coursera.org/learn/kotlin-for-java-developers[*Kotlin for Java Developers | Coursera*], a free course
** https://www.kotlinprimer.com/[The Kotlin Primer], tailor-made to facilitate Kotlin adoption inside Java-centric organizations
* If you use Intellij, Kotlin plugin comes bundled.
* If you use VS Code based IDEs (e.g. Cursor) install this official https://github.com/Kotlin/kotlin-lsp[Kotlin Language Server plugin]
Similar development aids should be present for other code editors too.

== Code Formatting

* This repo uses https://github.com/diffplug/spotless[*Spotless*] for formatting files, as this repo has code from more than one programming language.
* Please run `./gradlew spotlessApply` before check-in to fix any formatting errors.

TIP: If you're on Intellij, replace your kbd:[Cmd+Shift+L] habit with kbd:[Ctrl]-kbd:[Ctrl] and run `./gradlew spotlessApply` (Or the respective action if you're on Eclipse).
It may be slow for the first run, but later runs should be faster.

== Static Analysis

Vador uses https://www.jetbrains.com/qodana/[JetBrains Qodana] with the free JVM Community linter.
The scan is opt-in because it runs in Docker and is not part of `build` or `check`.
Docker must be running with at least 4 GB of memory available.

[source,bash]
----
./gradlew qodanaScan
----

The Gradle task generates Vador's KAPT sources and both modules' classes before analysis.
Results, including `qodana.sarif.json`, are written to `build/qodana/results`; the reusable linter cache is stored in `.qodana/cache`.
GitHub Actions runs pull-request scans without secrets or write permissions and retains the report as a seven-day artifact.
Trusted `master` pushes may additionally send results to Qodana Cloud and GitHub code scanning when `QODANA_TOKEN` is configured.

== Manual publishing

=== Gradle Nexus Publish Plugin

We use https://github.com/gradle-nexus/publish-plugin#publishing-to-maven-central-via-sonatype-central[Gradle Nexus Publish Plugin]
to publish to Maven Central. Follow the usage instructions to set up Sonatype credentials and add them to your `~/.gradle/gradle.properties`.

[source,bash]
----
sonatypeUsername=<your-username>
sonatypePassword=<your-password>
----

=== Versioning Strategy

====
<A>.<B>.<C>
====

* A = Broke something on purpose (Breaking API change)
* B = Profit (Feature / Improvement)
* C = Broke something by accident (Bug)

Follow the Versioning Strategy to increment the `vador.version` property in link:gradle.properties[gradle.properties].
For SNAPSHOT releases, add a `-SNAPSHOT` at the end of version number

=== Publish

Run this command to publish it to Nexus:

[source,bash]
----
./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Dorg.gradle.parallel=false --no-configuration-cache
----

* You can monitor for the new version jar to reflect in https://repo1.maven.org/maven2/com/salesforce/vador/vador/[Maven Central]. It usually takes less than 30 minutes.

== Code of Conduct
Please follow our link:CODE_OF_CONDUCT.md[Code of Conduct]

== License
By contributing your code,
you agree to license your contribution under the terms of our project link:LICENSE[]
and to sign the https://cla.salesforce.com/sign-cla[Salesforce CLA]
