= `validateAndFailFastForEach (with Pair for Failure)`
Gopal S Akshintala <gopalakshintala@gmail.com>
:Revision: 1.0
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:sectnums!:
:sourcedir: ../../../vador/src/main/java
:testdir: ../../../vador/src/test/java
:imagesdir: ../../images

This execution strategy lets you run validations for your batch data structure
and _fail-fast_ on the first failure for _each_ member in the batch i.e.,
if a member fails one of the validations,
it stops running further validations on that member and moves on to the next member in the batch. 

== Params

[cols="1,1,1,3"]
|===
|Param |Data type |Required? |Description

|`validatables`
|`List<ValidatableT>`
|Yes
|List of POJO/Beans under validation

|`pairForInvalidMapper`
|`(ValidatableT) -> PairT`
|Yes
|Function (mostly a getter) whose return value can be used as an identifier to identify the first failed member in `validatables`.

|`batchValidationConfig`
|`BatchValidationConfig`
|Yes
|Config for validation

|`failureForNullValidatable`
|`FailureT`
|No
|Failure to return if a member in `validatables` passed is `null`

|`throwableMapper`
|`(Throwable) -> FailureT?`
|No
|xref:../../../README.adoc#_what_if_there_is_an_exception_during_execution[Refer to this section]

|===

== Return

You can read more about `Either` data type https://docs.vavr.io/#_either[here].

`List<Either<Tuple2<PairT, FailureT>, ValidatableT>>` - One entry per member in the same order of `validatables`. 
If the member passes all validations, the result hold the validatable that is validated in the right state `Either.right(ValidatableT)`. 
Otherwise, the result will be `Either.left(Tuple2<PairT, FailureT>)`, holding the first failure for that validatable paired with an identifier of the failed member.
