= `validateAndFailFastForEach`
Gopal S Akshintala <gopala.akshintala@salesforce.com>
:Revision: 1.0
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:sectnums!:
:sourcedir: ../../../vader/src/main/java
:testdir: ../../../vader/src/test/java
:imagesdir: ../../images

This execution strategy lets you run validations for your batch data structure and fail-fast on the first failure for _each_ member in the batch i.e., if a member fails one of the validations, it stops running further validations on that members and moves on to the next member in the batch. 

== Params

[cols="1,1,1,3"]
|===
|Param |Data type |Required? |Description

|`validatables`
|`List<ValidatableT>`
|Yes
|List of POJO/Beans under validation

|`batchValidationConfig`
|link:../../config-dsl/BatchValidationConfig.adoc[`BatchValidationConfig`]
|Yes
|Config for Batch validation

|`failureForNullValidatable`
|`FailureT`
|No
|Failure to return if a member in `validatables` passed is `null`

|`throwableMapper`
|`(Throwable) -> FailureT?`
|No
|xref:../../../README.adoc#_what_if_there_is_an_exception_during_execution[Refer this section]

|===

== Return

You can read more about `Either` data type https://docs.vavr.io/#_either[here].

`List<Either<FailureT, ValidatableT>>` - One entry per member in the same order of `validatables`. 
If the member passes all validations, the result hold the validatable that is validated in the right state `Either.right(Validatable)`. 
Otherwise, the result will be `Either.left(Failure)`, holding the first failure for that validatable.
