= BatchValidationConfig DSL
Gopal S Akshintala <gopala.akshintala@salesforce.com>
:Revision: 1.0
:icons: font
:tip-caption: 💡
:caution-caption: ⚠️
:sourcedir: ../../src/main/java
:testdir: ../../src/test/java
:imagesdir: ../../images
:sectnums:
:listing-caption: Snippet
:toc:
:toc-placement: preamble

As the name indicates, use this to configure validation requirements for a data-structure that exists in a _Collection_ or a _Batch_, say `List<ValidatableT>`.
But why a new DSL, can't we just use `ValidationConfig` DSL and loop through each item and validate? `BatchValidationConfig` is a superset of `ValidationConfig` and we can configure more than just validations and required fields/Ids.
You can configure specifications that need context of the entire Batch.
For example, *Finding and Filtering/Failing Duplicates* based on a bean property. Let's see through an example:

== Example

ifdef::env-github[]

[source,java,indent=0]
----
class Bean {
  ID id;
}
----

endif::[]
ifndef::env-github[]

[source,java,indent=0]
----
include::{testdir}/org/revcloud/vader/runner/UtilsTest.java[tag=batch-bean]
----

endif::[]

=== Validation Requirements

* Validate a _Batch_ of these beans.
* Filter and Fail duplicates based on a bean property, say `id`

=== Demo

ifdef::env-github[]

[source,java,indent=0]
----
@DisplayName("FailForDuplicates configured. FAIL: NullValidatbles, FAIL: Duplicates")
@Test
void filterNullValidatablesAndFailDuplicates() {
final List<Bean> nullValidatables = List.of(null, null);
final var duplicateValidatables =
    List.of(
        new Bean(new ID("802xx000001ni4xAAA")),
        new Bean(new ID("802xx000001ni4x")),
        new Bean(new ID("802xx000001ni4x")));
final var validatables =
    nullValidatables
        .appendAll(duplicateValidatables)
        .appendAll(
            List.of(new Bean(new ID("1")), new Bean(new ID("2")), new Bean(new ID("3"))));

final var batchValidationConfig =
    BatchValidationConfig.<Bean, ValidationFailure>toValidate()
        .findAndFilterDuplicatesConfig(
            FilterDuplicatesConfig.<Bean, ValidationFailure>toValidate()
                .findAndFilterDuplicatesWith(
                    container -> container.getId().get18CharIdIfValid())
                .andFailDuplicatesWith(DUPLICATE_ITEM)
                .prepare())
        .prepare();
final var results =
    List.ofAll(
        findAndFilterInvalids(
            validatables.toJavaList(),
            NOTHING_TO_VALIDATE,
            batchValidationConfig.findAndFilterDuplicatesConfigs));

final var failedInvalids = results.take(2);
assertThat(failedInvalids).allMatch(r -> r.getLeft() == NOTHING_TO_VALIDATE);
final var failedDuplicates = results.drop(2).take(3);
assertThat(failedDuplicates).allMatch(r -> r.getLeft() == DUPLICATE_ITEM);

final var valids = results.drop(5);
assertTrue(valids.forAll(Either::isRight));
valids.forEachWithIndex(
    (r, i) -> assertEquals(String.valueOf(i + 1), r.get().getId().toString()));
}
----

endif::[]
ifndef::env-github[]

[source,java,indent=0]
----
include::{testdir}/org/revcloud/vader/runner/UtilsTest.java[tag=batch-bean-demo]
----

endif::[]

You can even add *Multiple filters* for filtering and failing duplicates on these criteria.

== Example

ifdef::env-github[]

[source,java,indent=0]
----
class MultiKeyBean {
  ID id1;
  ID id2;
}
----

endif::[]
ifndef::env-github[]

[source,java,indent=0]
----
include::{testdir}/org/revcloud/vader/runner/UtilsTest.java[tag=batch-bean-multikey]
----

endif::[]

=== Validation Requirements

* Filter and Fail duplicates on more than one filter.

=== Demo

ifdef::env-github[]

[source,java,indent=0]
----
@DisplayName(
  "Multiple Filters - FailForDuplicates configured. FAIL: NullValidatbles, FAIL: Duplicates")
@Test
void filterNullValidatablesAndFailDuplicatesForMultipleFilters() {
final List<MultiKeyBean> nullValidatables = List.of(null, null);
final var duplicateValidatables =
    List.of(
        new MultiKeyBean(new ID("802xx000001ni4xAAA"), new ID("802xx000001ni5xAAA")),
        new MultiKeyBean(new ID("802xx000001ni4x"), new ID("802xx000001ni4x")),
        new MultiKeyBean(new ID("802xx000001ni5x"), new ID("802xx000001ni4xAAA")));
final var validatables =
    nullValidatables
        .appendAll(duplicateValidatables)
        .appendAll(
            List.of(
                new MultiKeyBean(new ID("1"), new ID("1")),
                new MultiKeyBean(new ID("2"), new ID("2")),
                new MultiKeyBean(new ID("3"), new ID("3"))));

final var batchValidationConfig =
    BatchValidationConfig.<MultiKeyBean, ValidationFailure>toValidate()
        .findAndFilterDuplicatesConfig(
            FilterDuplicatesConfig.<MultiKeyBean, ValidationFailure>toValidate()
                .findAndFilterDuplicatesWith(
                    container ->
                        container.getId1() == null
                            ? null
                            : container.getId1().get18CharIdIfValid())
                .andFailDuplicatesWith(DUPLICATE_ITEM_1)
                .prepare())
        .findAndFilterDuplicatesConfig(
            FilterDuplicatesConfig.<MultiKeyBean, ValidationFailure>toValidate()
                .findAndFilterDuplicatesWith(
                    container ->
                        container.getId2() == null
                            ? null
                            : container.getId2().get18CharIdIfValid())
                .andFailDuplicatesWith(DUPLICATE_ITEM_2)
                .prepare())
        .prepare();
final var results =
    List.ofAll(
        findAndFilterInvalids(
            validatables.toJavaList(),
            NOTHING_TO_VALIDATE,
            batchValidationConfig.findAndFilterDuplicatesConfigs));

final var failedInvalids = results.take(2);
assertThat(failedInvalids).allMatch(r -> r.getLeft() == NOTHING_TO_VALIDATE);
final var failedDuplicates1 = results.drop(2).take(2);
assertThat(failedDuplicates1).allMatch(r -> r.getLeft() == DUPLICATE_ITEM_1);

final var failedDuplicates2 = results.drop(4).take(1);
assertThat(failedDuplicates2).allMatch(r -> r.getLeft() == DUPLICATE_ITEM_2);

final var valids = results.drop(5);
assertTrue(valids.forAll(Either::isRight));
valids.forEachWithIndex(
    (r, i) -> assertEquals(String.valueOf(i + 1), r.get().getId1().toString()));
}
----

endif::[]
ifndef::env-github[]

[source,java,indent=0]
----
include::{testdir}/org/revcloud/vader/runner/UtilsTest.java[tag=batch-bean-multikey-demo]
----

endif::[]

`FilterConfig` DSL is composed inside all `BatchValidationConfig` DSLs. There are more things that can be configured with this `FilterConfig` DSL.

* You may just choose to filter duplicates without failing them, by not configuring `andFailDuplicatesWith`.
* You may choose to fail a bean if the filter key specified is `null`, by configuring `andFailNullKeysWith`.
