[versions]
jdk = "25"
kotlin = "2.4.20-RC2"
java-vavr = "0.11.0"
kotlin-vavr = "0.10.2"
hamcrest-core = "3.0"
hamcrest-date = "2.0.8"
typeTools = "0.6.3"
assertj-vavr = "0.5.1"
reflection-util = "2.15.0" # 2.15.0 is Compatable with Java 11
nexus-publish = "2.0.0"
sonarqube = "6.3.1.5724"
apache-common-text-version = "1.15.0"
immutables = "2.12.2"

# Common dependencies
junit = "5.12.0"
kover = "0.9.9"
kotest = "5.9.1"
assertj-core = "3.27.7"
detekt = "2.0.0-alpha.6"
spotless = "8.10.1"
apache-log4j = "2.26.1"
testLogger = "4.0.0"
jetbrains-annotations = "26.1.0"

[libraries]
hamcrest-core = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest-core" }
hamcrest-date = { module = "org.exparity:hamcrest-date", version.ref = "hamcrest-date" }
java-vavr = { module = "io.vavr:vavr", version.ref = "java-vavr" }
kotlin-vavr = { module = "io.vavr:vavr-kotlin", version.ref = "kotlin-vavr" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
typeTools = { module = "net.jodah:typetools", version.ref = "typeTools" }
reflection-util = { module = "de.cronn:reflection-util", version.ref = "reflection-util" }
testLogger-gradle = { module = "com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin", version.ref = "testLogger" }
apache-common-text = { module = "org.apache.commons:commons-text", version.ref = "apache-common-text-version" }
immutables-value = { module = "org.immutables:value", version.ref = "immutables" }
immutables-value-annotations = { module = "org.immutables:value-annotations", version.ref = "immutables" }
kotest-assertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-frameworkEngine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runnerJUnit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
assertj-vavr = { module = "org.assertj:assertj-vavr", version.ref = "assertj-vavr" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "apache-log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "apache-log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "apache-log4j" }

# Gradle plugins
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradle = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
kover-gradle = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kover" }
spotless-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
nexus-publish-gradle = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
sonarqube-gradle = { module = "org.sonarqube:org.sonarqube.gradle.plugin", version.ref = "sonarqube" }

[bundles]
kotest = [
    "kotest-assertionsCore",
    "kotest-frameworkEngine",
    "kotest-property",
    "kotest-runnerJUnit5",
]
apache-log4j = ["log4j-api", "log4j-core", "log4j-slf4j2-impl"]

[plugins]
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
testLogger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
