/*
 * Copyright 2018 salesforce.com, inc.
 * All Rights Reserved
 * Company Confidential
 */

package consumer.representation;


import consumer.ConnectInputRepresentation;

import java.util.Date;


/**
 * Connect API input representation.
 *
 * @author gakshintala
 * @since 228
 */
public class ChildInputRepresentation extends ConnectInputRepresentation {

    private Double amount;
    private String paymentAuthorizationId;
    private String accountId;
    private Date effectiveDate;
    private String comments;
    private String clientContext;

    private boolean isSetAmount = false;
    private boolean isSetPaymentAuthorizationId = false;
    private boolean isSetAccountId = false;
    private boolean isSetEffectiveDate = false;
    private boolean isSetComments = false;
    private boolean isSetPaymentGroup = false;
    private boolean isSetClientContext = false;

    public Double getAmount() {
        return amount;
    }

    public void setAmount(final Double amount) {
        this.amount = amount;
        this.isSetAmount = true;
    }

    public boolean _isSetAmount() {
        return isSetAmount;
    }

    public String getPaymentAuthorizationId() {
        return paymentAuthorizationId;
    }

    public void setPaymentAuthorizationId(final String id) {
        this.paymentAuthorizationId = id;
        this.isSetPaymentAuthorizationId = true;
    }

    public boolean _isSetPaymentAuthorizationId() {
        return isSetPaymentAuthorizationId;
    }

    public Date getEffectiveDate() {
        return effectiveDate;
    }

    public void setEffectiveDate(final Date effectiveDate) {
        this.effectiveDate = effectiveDate;
        this.isSetEffectiveDate = true;
    }

    public boolean _isSetEffectiveDate() {
        return isSetEffectiveDate;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(final String id) {
        this.accountId = id;
        this.isSetAccountId = true;
    }

    public boolean _isSetAccountId() {
        return isSetAccountId;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(final String comments) {
        this.comments = comments;
        this.isSetComments = true;
    }

    public boolean _isSetComments() {
        return isSetComments;
    }

    public boolean _isSetPaymentGroup() {
        return isSetPaymentGroup;
    }

    public String getClientContext() {
        return clientContext;
    }

    public void setClientContext(final String clientContext) {
        this.clientContext = clientContext;
        this.isSetClientContext = true;
    }

    public boolean _isSetClientContext() {
        return isSetClientContext;
    }

    //Autogenerated tostring
    //Javac automatically uses StringBuilder https://stackoverflow.com/questions/14088414/eclipse-autogenerated-tostring-method
    @Override
    public String toString() {
        return "CaptureInputRepresentation{" +
               "amount=" + amount +
               ", paymentAuthorizationId='" + paymentAuthorizationId + '\'' +
               ", accountId=" + accountId +
               ", effectiveDate=" + effectiveDate +
               ", comments='" + comments + '\'' +
               ", clientContext='" + clientContext + '\'' +
               ", isSetAmount=" + isSetAmount +
               ", isSetPaymentAuthorizationId=" + isSetPaymentAuthorizationId +
               ", isSetAccountId=" + isSetAccountId +
               ", isSetEffectiveDate=" + isSetEffectiveDate +
               ", isSetComments=" + isSetComments +
               ", isSetPaymentGroup=" + isSetPaymentGroup +
               ", isSetClientContext=" + isSetClientContext +
               '}';
    }
}
