= Nested Validation
Gopal S Akshintala <gopala.akshintala@salesforce.com>
:Revision: 1.0
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:prewrap!:
:sourcedir: ../../../vador/src/main/java
:testdir: ../../../vador/src/test/java
:imagesdir: ../../images/config-dsl

To validate a Nested Data-structures (Eg: `ContainerT` HAS-A `MemberT`). 
Based on type of `ContainerT` and `MemberT`, the below table should guide you how to compose their Validation Execution results.
 For example, the below table:

[%autowidth]
[cols="1h,1"]
|===
| Type | Non-Batch
| Strategy | Fail Fast
| Result | `Optional<FailureT>`
|===

indicates that the `ContainerT` is a Non-Batch type, with `failFast` strategy, the result of such validation execution shall be of type `Optional<FailureT>`.

== Level-Order Validation

This lets you validate all the nodes at `ContainerT` level first and then validate their HAS-A `MemberT` nodes in next level:

[cols="4a,4a,2"]
|===
|Container |Member |Strategy

|
[cols="1"]
!===
! Non-Batch
! Fail Fast
! `Optional<FailureT>`
!===

|[cols="1"]

!===
! Non-Batch ! Fail Fast ! `Optional<FailureT>`
!===

|Compose `Optional` results with ValidationConfig link:../ValidationConfig.adoc#_nested-non-batch-non-batch-level-order[like this]
|[cols="1"]

!===
! Non-Batch ! Fail Fast ! `Optional<FailureT>`
!===

|[cols="1"]

!===
! Batch ! Fail Fast for Any ! `Optional<FailureT>`
!===

|Compose `Optional` results with ValidationConfig link:../ValidationConfig.adoc#_nested-non-batch-non-batch-level-order[similar to this]

|[cols="1"]

!===
! Non-Batch ! Fail Fast ! `Optional<FailureT>`
!===

|[cols="1"]

!===
! Batch ! Fail Fast for Each ! `List<Either<FailureT, ValidatableT>>`
!===

|TBD

|[cols="1"]

!===
! Batch ! Fail Fast for Any ! `Optional<FailureT>`
!===

|[cols="1"]

!===
! Non-Batch ! Fail Fast ! `Optional<FailureT>`
!===

|Compose `Optional` results with ValidationConfig link:../ValidationConfig.adoc#_nested-non-batch-non-batch-level-order[similar to this]

|[cols="1"]

!===
! Batch ! Fail Fast for Each ! `List<Either<FailureT, ValidatableT>>`
!===

|[cols="1"]

!===
! Non-Batch ! Fail Fast ! `Optional<FailureT>`
!===

|TBD

|[cols="1"]

!===
! Batch ! Fail Fast for Any ! `Optional<FailureT>`
!===

|[cols="1"]

!===
! Batch ! Fail Fast for Any ! `Optional<FailureT>`
!===

|link:BatchOfBatch1ValidationConfig.adoc[BatchOfBatch1ValidationConfig] if needed with Pair.
Otherwise, compose `Optional` results with ValidationConfig link:../ValidationConfig.adoc#_nested-non-batch-non-batch-level-order[similar to this]

|[cols="1"]

!===
! Batch ! Fail Fast for Each ! `List<Either<FailureT, ValidatableT>>`
!===

|[cols="1"]

!===
! Batch ! Fail Fast for Each ! `List<Either<FailureT, ValidatableT>>`
!===

|link:BatchOfBatch1ValidationConfig.adoc[BatchOfBatch1ValidationConfig]

|===

WARNING: Some of the above are TBD or may support only upto a nesting depth of 1.
As we work on addressing more complex use cases, there is another way where you can manually club Container and Member validations

== How to combine Container & Member validators?

But, there's a catch!
A List of Validators for a container node consists of a mix of all container validators and all its nested member validators.
But they can't be put under one `List`, as they are functions on different Data Types.

[source,java,indent=0,options="nowrap"]
----
ValidatorEtr<Container, ValidationFailure> containerValidator =...; // Apply same analogy for Validator
ValidatorEtr<Member, ValidationFailure> memberValidator =...;
List.of(containerValidator, memberValidator); // ^^^ Compile Error
----

So all nested member validators need to be lifted to the container type, essentially changing their type matching with the Container's, like: `ValidatorEtr<Container, ValidationFailure>`.

We can achieve this with `com.salesforce.vador.lift.++*++Util` functions.
These are *Higher-Order Functions* which *lift* member validator to the container type.
This takes a `containerToMemberMapper` which is the function to extract member-bean from container-bean.

[source,java,indent=0,options="nowrap"]
----
ValidatorEtr<Member, ValidationFailure> memberValidator =...;
ValidatorEtr<Container, ValidationFailure> liftedMemberValidator =...;
List.of(containerValidator, liftToContainerValidatorType(memberValidator, containerToMemberMapper)); // Happy Compiler :)
----

This way, we can configure a *Chain* of validators in-order, sorting out all the container-member dependencies.
This is nothing but, the most popular *Chain of Responsibility* Design pattern, with a functional touch-up.

=== Aggregation Util: To lift Member validator to Container validator type

These are available for both `Validator` and `ValidatorEtr`.

[cols="<,<"]
|===
|liftToContainerValidatorType |liftAllToContainerValidatorType
|liftToContainerValidatorType |liftAllToContainerValidatorType
|===

TIP: If the interdependencies between Container-Member happens to be more complex, we may end-up with _Graph_ relationship, 
but we can easily _flatten_ it into a Chain with a simple _Topological Sort_.


== How to combine Validators & ValidatorEtrs?

Similarly, Vador has utils to lift `Validator` to `ValidatorEtr`.
This is handy, when you have a mix of validations, and they all need to be of the same type to stitch them together.

=== Validator Util: To lift Simple validator to ValidatorEtr type

[cols="<,<"]
|===
|lift |liftAll
|===
