= Validation Configuration
Gopal S Akshintala <gopala.akshintala@salesforce.com>
:Revision: 1.0
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:toc-placement: preamble
:imagesdir: images
:testdir: ../vader/src/test/java
:prewrap!:

== What' Configuration?

A config object is 1-1 mapped with a Data Structure, and holds all the information/requirements/specifications required to validate that Data-structure.

== How to construct a Config Object 🔮?

Dont' worry, different flavors of link:config-dsl/dsl-driven-validation.adoc[Config DSLs] are here to co-pilot with you, to prepare the config instance as per your validation requirements.
These DSL methods follow the https://blogs.oracle.com/javamagazine/post/exploring-joshua-blochs-builder-design-pattern-in-java[Builder Pattern], where you instantiate the Builder like this:

[source,java,indent=0,options="nowrap"]
.++*++ValidationConfig
----
*ValidationConfig.<ValidatableT, FailureT>toValidate() // <1><2>
----
<1> ValidatableT - Represents the data-type under validation.
<2> FailureT - Represents the consumer data-type that represents a failure.

NOTE: As you notice, these API methods are generic and Vader is agnostic of the consumer's `ValidatableT` or `FailureT`.

=== `withValidator(s)`

This is used to wire link:validator-types.adoc#_validator[`Validator`] type lambdas into the config. This accepts a Tuple (Pair) of:

* `java.util.Collection<Validator>` - Collections of Validators. 
* `Failure` - Consumer defined value representing no-failure (or success). Vader recognizes that a validation passed, only if a validator returns this value.

TIP: If you need an order of execution (say, ascending order of validation cost), 
all you need is _chain_ your validators in an Ordered List (like `java.util.List`) to maintain the sequence of validations.

ifdef::env-github[]

[source,java,indent=0,options="nowrap"]
.link:{testdir}/org/revcloud/vader/runner/VaderTest.java[VaderTest.java, tag=withValidators]
----
final Validator<Bean, ValidationFailure> validator1 = bean -> NONE;
final Validator<Bean, ValidationFailure> validator2 = bean -> NONE;
final Validator<Bean, ValidationFailure> validator3 = bean -> UNKNOWN_EXCEPTION;
final List<Validator<Bean, ValidationFailure>> validatorChain =
    List.of(validator1, validator2, validator3);
final var validationConfig =
    ValidationConfig.<Bean, ValidationFailure>toValidate()
        .withValidators(Tuple.of(validatorChain, NONE))
        .prepare();
----

endif::[]
ifndef::env-github[]

[source,java,indent=0,options="nowrap"]
.link:{testdir}/org/revcloud/vader/runner/VaderTest.java[VaderTest.java, tag=withValidators]
----
include::{testdir}/org/revcloud/vader/runner/VaderTest.java[tag=withValidators]
----

endif::[]

[.lead]
But config does more than just wiring validations.
